{{- $dpl := dict "Values" .Values "Chart" .Chart "Component" "deployment" }}
{{- $repl := dict "Values" .Values "Chart" .Chart "Component" "replica" }}
{{- $ctr := dict "Values" .Values "Chart" .Chart "Component" "container" }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "common.name" $dpl }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" $dpl | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
{{ include "common.labels" $repl | indent 6 }}
  template:
    metadata:
      labels:
{{ include "common.labels" $repl | indent 8 }}
    spec:
{{- if .Values.affinity.crossZone }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
{{ include "common.labels" $repl | indent 18 }}
              topologyKey: kubernetes.io/hostname
{{- end }}
      containers:
        - name: {{ include "common.name" $ctr }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
{{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
{{- end }}
{{- if .Values.resources }}
          resources:
{{- if .Values.resources.requests }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
{{- end -}}
{{ if .Values.resources.limits }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
{{- end -}}
{{- end -}}