apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
{{ include "helm-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.exposePort }}
    # - port: {{ .Values.service.port }}
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
      # targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
